title: huis 62 Guest Manual
description: 
theme: just-the-docs

url: https://marcusgmueller.github.io/guestmanual

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
